# Carnevale Companion — Backend
# Copyright (C) 2026 Anachrion and contributors
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Exports the authored catalog to versioned files, and imports it back. This is what makes the
# database-as-source-of-truth safe: the catalog a game creator builds in the production backoffice
# lives only on that one server's disk until it is snapshotted here, into git, where it is an
# off-box backup and a reviewable diff. Import rebuilds that catalog in another environment (a
# fresh prod, a teammate's machine).
#
# What is captured: profiles (stats, keywords, abilities), their weapons and special rules (shared
# records, linked by a stable key), their card references, and their illustration records —
# *including the uploaded image bytes*, so art added in production is not lost when the server is
# rebuilt. What is not: render bookkeeping (internal_version, the digests), which is regenerated by
# rendering, and player data, which is not catalog.
#
# Import is additive and idempotent — find-or-update by natural key — so it is safe to run on a
# fresh database (disaster recovery, a new environment) and safe to re-run. It never deletes, so a
# record removed from the snapshot is left in place rather than cascaded through player data; prune
# those by hand if ever needed.
class CatalogSnapshot
  DEFAULT_DIR = Rails.root.join("db", "catalog").freeze
  BLOBS_SUBDIR = "blobs".freeze

  PROFILE_COLUMNS = %w[name faction version].concat(Catalog::Profile::STATS.map(&:to_s)).freeze
  WEAPON_COLUMNS = %w[name damage evasion penetration range abilities].freeze
  RULE_COLUMNS = %w[name description spell_name spell_cost spell_difficulty spell_description].freeze

  def self.export(dir: DEFAULT_DIR) = new(dir).export
  def self.import(dir: DEFAULT_DIR) = new(dir).import

  def initialize(dir)
    @dir = Pathname(dir)
    @blobs = @dir.join(BLOBS_SUBDIR)
  end

  # ── Export ────────────────────────────────────────────────────────────────────
  def export
    FileUtils.mkdir_p(@blobs)

    weapons = Catalog::Weapon.order(:name, :id).to_a
    rules   = Catalog::SpecialRule.order(:name, :id).to_a
    @weapon_key = stable_keys(weapons) { |w| w.name }
    @rule_key   = stable_keys(rules) { |r| r.name.presence || r.spell_name }

    write_yaml("weapons.yml", weapons.map { |w| { "key" => @weapon_key[w.id] }.merge(w.slice(*WEAPON_COLUMNS)) })
    write_yaml("special_rules.yml", rules.map { |r| { "key" => @rule_key[r.id] }.merge(r.slice(*RULE_COLUMNS)) })
    write_yaml("profiles.yml", exported_profiles)

    { weapons: weapons.size, special_rules: rules.size, profiles: Catalog::Profile.count, blobs: @blobs.children.count { |c| c.file? } }
  end

  # ── Import ────────────────────────────────────────────────────────────────────
  def import
    tally = Hash.new(0)

    ActiveRecord::Base.transaction do
      weapon_by_key = upsert_shared(read_yaml("weapons.yml"), Catalog::Weapon, WEAPON_COLUMNS, tally, :weapons)
      rule_by_key   = upsert_shared(read_yaml("special_rules.yml"), Catalog::SpecialRule, RULE_COLUMNS, tally, :special_rules)

      read_yaml("profiles.yml").each do |data|
        import_profile(data, weapon_by_key, rule_by_key, tally)
      end
    end

    # An import can rewrite any profile's ducats/keywords, which feed gang validity — recompute the
    # cached selection_valid/selection_errors for every existing gang so they don't read stale (B-24).
    Gang::List.find_each(&:refresh_selection_validity)

    tally
  end

  private

  # ── Export helpers ──────────────────────────────────────────────────────────────
  def exported_profiles
    scope = Catalog::Profile
      .includes(:card_references, { profile_weapons: :weapon }, { profile_special_rules: :special_rule },
                illustrations: { image_attachment: :blob })
      .order(:faction, :name, :id)

    scope.map do |profile|
      profile.slice(*PROFILE_COLUMNS).merge(
        "keywords" => profile.keywords,
        "abilities" => profile.abilities,
        "weapons" => profile.profile_weapons.sort_by(&:position).map { |pw| @weapon_key[pw.weapon_id] },
        "special_rules" => profile.profile_special_rules.sort_by(&:position).map { |pr| @rule_key[pr.special_rule_id] },
        "card_references" => profile.card_references.sort_by(&:identifier).map { |cr| cr.slice("identifier", "name", "illustration_number") },
        "illustrations" => profile.illustrations.sort_by(&:number).map { |illus| exported_illustration(profile, illus) }
      )
    end
  end

  def exported_illustration(profile, illus)
    data = illus.slice("number", "path", "offset_x", "offset_y", "zoom", "flipped")
    data["image"] = export_blob(profile, illus) if illus.image.attached?
    data
  end

  # Writes the uploaded image bytes to blobs/ and returns the filename to record in the YAML. Named
  # after the profile's anchor identifier and the illustration number, so it is stable and unique.
  def export_blob(profile, illus)
    ext = illus.image.filename.extension.presence || "bin"
    filename = "#{profile_anchor(profile)}-illus#{illus.number}.#{ext}"
    @blobs.join(filename).binwrite(illus.image.download)
    filename
  end

  # A profile's stable identity across environments: its first card reference's identifier, which
  # is globally unique. (Every profile has at least one.)
  def profile_anchor(profile)
    profile.card_references.min_by(&:identifier)&.identifier || "profile-#{profile.name.parameterize}"
  end

  # A deterministic, collision-free key per shared record, so profiles can reference their weapons
  # and rules by something stable — names are not unique in the catalog, ids are not portable.
  def stable_keys(records)
    used = Hash.new(0)
    records.each_with_object({}) do |record, map|
      base = yield(record).to_s.parameterize.presence || "item"
      used[base] += 1
      map[record.id] = used[base] == 1 ? base : "#{base}-#{used[base]}"
    end
  end

  # ── Import helpers ──────────────────────────────────────────────────────────────
  # Upsert weapons or special rules, returning a key => record map for wiring up profiles. Matched
  # by their full attribute set, so identical rows collapse and same-named-but-different rows stay
  # distinct — the natural-key problem the export's `key` sidesteps for associations. json columns
  # (a weapon's abilities) are compared in Ruby: the `json` type has no `=` operator to query on.
  def upsert_shared(rows, klass, columns, tally, bucket)
    json_columns = columns.select { |c| klass.columns_hash[c].type == :json }
    scalar_columns = columns - json_columns

    rows.each_with_object({}) do |row, map|
      candidates = klass.where(row.slice(*scalar_columns))
      record = candidates.detect { |c| json_columns.all? { |col| c[col] == row[col] } } ||
               klass.create!(row.slice(*columns)).tap { tally[bucket] += 1 }
      map[row.fetch("key")] = record
    end
  end

  def import_profile(data, weapon_by_key, rule_by_key, tally)
    identifiers = data.fetch("card_references").map { |cr| cr.fetch("identifier") }
    existing = Catalog::CardReference.where(identifier: identifiers).first&.profile
    profile = existing || Catalog::Profile.new
    was_new = profile.new_record?

    profile.assign_attributes(data.slice(*PROFILE_COLUMNS).merge(
      "keywords" => data.fetch("keywords"), "abilities" => data.fetch("abilities")
    ))
    profile.save!
    tally[was_new ? :profiles_created : :profiles_updated] += 1

    import_card_references(profile, data.fetch("card_references"))
    import_illustrations(profile, data.fetch("illustrations"))
    profile.replace_weapons!(data.fetch("weapons").map { |k| weapon_by_key.fetch(k).id })
    profile.replace_special_rules!(data.fetch("special_rules").map { |k| rule_by_key.fetch(k).id })
  end

  def import_card_references(profile, rows)
    rows.each do |row|
      ref = Catalog::CardReference.find_or_initialize_by(identifier: row.fetch("identifier"))
      ref.assign_attributes(profile: profile, name: row.fetch("name"), illustration_number: row.fetch("illustration_number"))
      ref.save!
    end
  end

  def import_illustrations(profile, rows)
    rows.each do |row|
      illus = profile.illustrations.find_or_initialize_by(number: row.fetch("number"))
      illus.assign_attributes(row.slice("path", "offset_x", "offset_y", "zoom", "flipped"))
      illus.path ||= ""
      attach_blob(illus, row["image"]) if row["image"].present?
      illus.save!
    end
  end

  def attach_blob(illus, filename)
    file = @blobs.join(filename)
    return unless file.exist?

    illus.image.purge if illus.image.attached?
    illus.image.attach(io: file.open("rb"), filename: filename)
  end

  # ── IO ──────────────────────────────────────────────────────────────────────────
  # as_json first, so the file holds plain Hashes/Arrays with string keys — ActiveRecord#slice
  # returns HashWithIndifferentAccess, which Psych would tag with its class and safe_load reject.
  def write_yaml(name, data)
    @dir.join(name).write(data.as_json.to_yaml)
  end

  def read_yaml(name)
    path = @dir.join(name)
    path.exist? ? YAML.safe_load(path.read) : []
  end
end
