services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: carnevale
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carnevale_backend_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
