references = [
  # Doctors
  { name: "Doctor of the Mind",             identifier: "doctors-doctor-of-the-mind",             faction: "doctors", cost: 22 },
  { name: "Master of Necromantic Studies",  identifier: "doctors-master-of-necromantic-studies",  faction: "doctors", cost: 23 },
  { name: "Master of Arcane Security",      identifier: "doctors-master-of-arcane-security",      faction: "doctors", cost: 27 },
  { name: "Master of Zoology",              identifier: "doctors-master-of-zoology",              faction: "doctors", cost: 20 },
  { name: "Plague Doctor",                  identifier: "doctors-plague-doctor",                  faction: "doctors", cost: 21 },
  { name: "Patient 42",                     identifier: "doctors-patient-42",                     faction: "doctors", cost: 14 },
  { name: "The Being",                      identifier: "doctors-the-being",                      faction: "doctors", cost: 15 },
  { name: "The Unholy Union",               identifier: "doctors-the-unholy-union",               faction: "doctors", cost: 45 },
  { name: "Brined Horror",                  identifier: "doctors-brined-horror",                  faction: "doctors", cost: 19 },
  { name: "Doctor of Blood",                identifier: "doctors-doctor-of-blood",                faction: "doctors", cost: 16 },
  { name: "Doctor of Divine Probabilities", identifier: "doctors-doctor-of-divine-probabilities", faction: "doctors", cost: 15 },
  { name: "Doctor of Tides",                identifier: "doctors-doctor-of-tides",                faction: "doctors", cost: 18 },
  { name: "Doctor of Poisons",              identifier: "doctors-doctor-of-poisons",              faction: "doctors", cost: 13 },
  { name: "Doctor of the Beasts",           identifier: "doctors-doctor-of-the-beasts",           faction: "doctors", cost: 14 },
  { name: "Doctor of the Firmament",        identifier: "doctors-doctor-of-the-firmament",        faction: "doctors", cost: 16 },
  { name: "Ethereal Assassin",              identifier: "doctors-ethereal-assassin",              faction: "doctors", cost: 13 },
  { name: "Ethereal Snatcher",              identifier: "doctors-ethereal-snatcher",              faction: "doctors", cost: 15 },
  { name: "Alchemist Doctor",               identifier: "doctors-alchemist-doctor",               faction: "doctors", cost: 13 },
  { name: "Morgue Doctor",                  identifier: "doctors-morgue-doctor",                  faction: "doctors", cost: 15 },
  { name: "Marine Biologist",               identifier: "doctors-marine-biologist",               faction: "doctors", cost: 14 },
  { name: "Ordnance Doctor",                identifier: "doctors-ordnance-doctor",                faction: "doctors", cost: 15 },
  { name: "Unleashed Madman",               identifier: "doctors-unleashed-madman",               faction: "doctors", cost: 15 },
  { name: "Voltage Bombardiers",            identifier: "doctors-voltage-bombardiers",            faction: "doctors", cost: 12 },
  { name: "Warden",                         identifier: "doctors-warden",                         faction: "doctors", cost: 13 },
  { name: "Apprentice Doctor",              identifier: "doctors-apprentice-doctor-a",            faction: "doctors", cost: 12 },
  { name: "Apprentice Doctor",              identifier: "doctors-apprentice-doctor-b",            faction: "doctors", cost: 12 },
  { name: "Basilisk",                       identifier: "doctors-basilisk",                       faction: "doctors", cost: 13 },
  { name: "Carrion",                        identifier: "doctors-carrion-a",                      faction: "doctors", cost: 10 },
  { name: "Carrion",                        identifier: "doctors-carrion-b",                      faction: "doctors", cost: 10 },
  { name: "Crocodile",                      identifier: "doctors-crocodile",                      faction: "doctors", cost: 14 },
  { name: "Doctor of Venesection",          identifier: "doctors-doctor-of-venesection-a",        faction: "doctors", cost: 10 },
  { name: "Doctor of Venesection",          identifier: "doctors-doctor-of-venesection-b",        faction: "doctors", cost: 10 },
  { name: "Diving Assistant",               identifier: "doctors-diving-assistant",               faction: "doctors", cost: 13 },
  { name: "Electron Cannoneer",             identifier: "doctors-electron-cannoneer",             faction: "doctors", cost: 12 },
  { name: "Ghoul",                          identifier: "doctors-ghoul-a",                        faction: "doctors", cost:  6 },
  { name: "Ghoul",                          identifier: "doctors-ghoul-b",                        faction: "doctors", cost:  6 },
  { name: "Gorilla",                        identifier: "doctors-gorilla",                        faction: "doctors", cost: 13 },
  { name: "Hippocampus",                    identifier: "doctors-hippocampus",                    faction: "doctors", cost: 19 },
  { name: "Hippogryph",                     identifier: "doctors-hippogryph",                     faction: "doctors", cost:  7 },
  { name: "Hollowman",                      identifier: "doctors-hollowman-a",                    faction: "doctors", cost:  6 },
  { name: "Hollowman",                      identifier: "doctors-hollowman-b",                    faction: "doctors", cost:  6 },
  { name: "Harvester",                      identifier: "doctors-harvester",                      faction: "doctors", cost: 11 },
  { name: "Husk",                           identifier: "doctors-husk-a",                         faction: "doctors", cost:  4 },
  { name: "Husk",                           identifier: "doctors-husk-b",                         faction: "doctors", cost:  4 },
  { name: "Lab Assistant",                  identifier: "doctors-lab-assistant-a",                faction: "doctors", cost: 10 },
  { name: "Lab Assistant",                  identifier: "doctors-lab-assistant-b",                faction: "doctors", cost: 10 },
  { name: "Lion",                           identifier: "doctors-lion",                           faction: "doctors", cost: 12 },
  { name: "Madman",                         identifier: "doctors-madman-a",                       faction: "doctors", cost:  5 },
  { name: "Madman",                         identifier: "doctors-madman-b",                       faction: "doctors", cost:  5 },
  { name: "Manticore",                      identifier: "doctors-manticore",                      faction: "doctors", cost:  9 },
  { name: "Mermaid",                        identifier: "doctors-mermaid",                        faction: "doctors", cost: 13 },
  { name: "Monstrosity",                    identifier: "doctors-monstrosity",                    faction: "doctors", cost:  9 },
  { name: "Nurse",                          identifier: "doctors-nurse-a",                        faction: "doctors", cost:  7 },
  { name: "Nurse",                          identifier: "doctors-nurse-b",                        faction: "doctors", cost:  7 },
  { name: "Rhino",                          identifier: "doctors-rhino",                          faction: "doctors", cost: 15 },
  { name: "Shackled Feaster",               identifier: "doctors-shackled-feaster",               faction: "doctors", cost:  7 },

  # Gifted
  { name: "Il Capitano",            identifier: "gifted-il-capitano",           faction: "gifted", cost: 19 },
  { name: "La Signora",             identifier: "gifted-la-signora",            faction: "gifted", cost: 18 },
  { name: "The Duke",               identifier: "gifted-the-duke",              faction: "gifted", cost: 22 },
  { name: "The Aberration",         identifier: "gifted-the-aberration",        faction: "gifted", cost: 23 },
  { name: "Artisan Elena",          identifier: "gifted-artisan-elena",         faction: "gifted", cost: 17 },
  { name: "Black Spectre",          identifier: "gifted-black-spectre",         faction: "gifted", cost: 30 },
  { name: "Burattino",              identifier: "gifted-burattino",             faction: "gifted", cost: 15 },
  { name: "Fadhila",                identifier: "gifted-fadhila",               faction: "gifted", cost: 19 },
  { name: "Fate",                   identifier: "gifted-fate",                  faction: "gifted", cost: 18 },
  { name: "Francisco De Lorme",     identifier: "gifted-francisco-de-lorme",    faction: "gifted", cost: 16 },
  { name: "Harbinger's Reflection", identifier: "gifted-harbingers-reflection", faction: "gifted", cost: 17 },
  { name: "Harlequin",              identifier: "gifted-harlequin",             faction: "gifted", cost: 18 },
  { name: "Il Mentore",             identifier: "gifted-il-mentore",            faction: "gifted", cost: 16 },
  { name: "Innamorati",             identifier: "gifted-innamorati",            faction: "gifted", cost: 13 },
  { name: "Justice",                identifier: "gifted-justice",               faction: "gifted", cost: 18 },
  { name: "Marco Leontus",          identifier: "gifted-marco-leontus",         faction: "gifted", cost: 15 },
  { name: "Master Gerhard",         identifier: "gifted-master-gerhard",        faction: "gifted", cost: 16 },
  { name: "Maria Fioritura",        identifier: "gifted-maria-fioritura",       faction: "gifted", cost: 18 },
  { name: "Painted Protector",      identifier: "gifted-painted-protector",     faction: "gifted", cost:  0 },
  { name: "Senshi the Undying",     identifier: "gifted-senshi-the-undying",    faction: "gifted", cost: 20 },
  { name: "Solus Hydraea",          identifier: "gifted-solus-hydraea",         faction: "gifted", cost: 17 },
  { name: "The Mask Maker",         identifier: "gifted-the-mask-maker",        faction: "gifted", cost: 14 },
  { name: "White Dove",             identifier: "gifted-white-dove",            faction: "gifted", cost: 21 },
  { name: "Zovena Vela",            identifier: "gifted-zovena-vela",           faction: "gifted", cost: 15 },
  { name: "Brighella",              identifier: "gifted-brighella",             faction: "gifted", cost: 13 },
  { name: "Colombina",              identifier: "gifted-colombina",             faction: "gifted", cost: 10 },
  { name: "Coviello",               identifier: "gifted-coviello",              faction: "gifted", cost: 11 },
  { name: "The Demolitionist",      identifier: "gifted-the-demolitionist",     faction: "gifted", cost: 13 },
  { name: "Escaped Madman",         identifier: "gifted-escaped-madman",        faction: "gifted", cost: 16 },
  { name: "Il Dottore",             identifier: "gifted-il-dottore",            faction: "gifted", cost: 12 },
  { name: "Mezzetino",              identifier: "gifted-mezzetino",             faction: "gifted", cost: 13 },
  { name: "Pantaleone",             identifier: "gifted-pantaleone",            faction: "gifted", cost: 10 },
  { name: "Scapino",                identifier: "gifted-scapino",               faction: "gifted", cost:  0 },
  { name: "Starspawn",              identifier: "gifted-starspawn",             faction: "gifted", cost: 15 },
  { name: "Pierrot",                identifier: "gifted-pierrot-a",             faction: "gifted", cost:  8 },
  { name: "Pierrot",                identifier: "gifted-pierrot-b",             faction: "gifted", cost:  8 },

  # Guild
  { name: "Capodecina",        identifier: "guild-capodecina",        faction: "guild", cost: 20 },
  { name: "Harbourmaster",     identifier: "guild-harbourmaster",     faction: "guild", cost: 21 },
  { name: "King For a Day",    identifier: "guild-king-for-a-day",   faction: "guild", cost: 16 },
  { name: "Madame",            identifier: "guild-madame",            faction: "guild", cost: 20 },
  { name: "Ostrich King?!",    identifier: "guild-ostrich-king",      faction: "guild", cost: 19 },
  { name: "Prince of Thieves", identifier: "guild-prince-of-thieves", faction: "guild", cost: 23 },
  { name: "Baba-Yaga",         identifier: "guild-baba-yaga",         faction: "guild", cost: 19 },
  { name: "Black Lamp",        identifier: "guild-black-lamp",        faction: "guild", cost: 17 },
  { name: "Ebenezer Chummage", identifier: "guild-ebenezer-chummage", faction: "guild", cost: 18 },
  { name: "Ostrich Chariot?!", identifier: "guild-ostrich-chariot",   faction: "guild", cost: 34 },
  { name: "Rialto Assassin",   identifier: "guild-rialto-assassin",   faction: "guild", cost: 16 },
  { name: "Bloodletter",       identifier: "guild-bloodletter",       faction: "guild", cost: 16 },
  { name: "Blood Matron",      identifier: "guild-blood-matron",      faction: "guild", cost: 15 },
  { name: "Barber",            identifier: "guild-barber",            faction: "guild", cost: 12 },
  { name: "Baroni",            identifier: "guild-baroni",            faction: "guild", cost: 15 },
  { name: "Brewer",            identifier: "guild-brewer",            faction: "guild", cost: 15 },
  { name: "Brute",             identifier: "guild-brute",             faction: "guild", cost: 13 },
  { name: "Butcher",           identifier: "guild-butcher",           faction: "guild", cost: 13 },
  { name: "Dancer",            identifier: "guild-dancer",            faction: "guild", cost: 14 },
  { name: "Death Duellist",    identifier: "guild-death-duellist",    faction: "guild", cost: 14 },
  { name: "Fisherman",         identifier: "guild-fisherman",         faction: "guild", cost: 14 },
  { name: "Recruiter",         identifier: "guild-recruiter",         faction: "guild", cost: 14 },
  { name: "Seamstress",        identifier: "guild-seamstress",        faction: "guild", cost: 14 },
  { name: "Shadow Assassin",   identifier: "guild-shadow-assassin",   faction: "guild", cost: 14 },
  { name: "Smuggler",          identifier: "guild-smuggler",          faction: "guild", cost: 13 },
  { name: "Thief",             identifier: "guild-thief",             faction: "guild", cost: 14 },
  { name: "Very Loud Ostrich", identifier: "guild-very-loud-ostrich", faction: "guild", cost: 16 },
  { name: "Whaler",            identifier: "guild-whaler",            faction: "guild", cost: 17 },
  { name: "Witch",             identifier: "guild-witch",             faction: "guild", cost: 16 },
  { name: "Arbalest",          identifier: "guild-arbalest-a",        faction: "guild", cost: 10 },
  { name: "Arbalest",          identifier: "guild-arbalest-b",        faction: "guild", cost: 10 },
  { name: "Beggar",            identifier: "guild-beggar-a",          faction: "guild", cost:  5 },
  { name: "Beggar",            identifier: "guild-beggar-b",          faction: "guild", cost:  5 },
  { name: "Blooded",           identifier: "guild-blooded-a",         faction: "guild", cost:  5 },
  { name: "Blooded",           identifier: "guild-blooded-b",         faction: "guild", cost:  5 },
  { name: "Blood Courier",     identifier: "guild-blood-courier",     faction: "guild", cost: 13 },
  { name: "Poacher",           identifier: "guild-poacher-a",         faction: "guild", cost: 11 },
  { name: "Poacher",           identifier: "guild-poacher-b",         faction: "guild", cost: 11 },
  { name: "Pulcinella",        identifier: "guild-pulcinella-a",      faction: "guild", cost:  8 },
  { name: "Pulcinella",        identifier: "guild-pulcinella-b",      faction: "guild", cost:  8 },
  { name: "Shipwright",        identifier: "guild-shipwright",        faction: "guild", cost: 12 },
  { name: "Escort",            identifier: "guild-escort",            faction: "guild", cost: 12 },
  { name: "Firebreather",      identifier: "guild-firebreather",      faction: "guild", cost: 10 },
  { name: "Gondolier",         identifier: "guild-gondolier-a",       faction: "guild", cost: 11 },
  { name: "Gondolier",         identifier: "guild-gondolier-b",       faction: "guild", cost: 11 },
  { name: "Harlot",            identifier: "guild-harlot-a",          faction: "guild", cost: 10 },
  { name: "Harlot",            identifier: "guild-harlot-b",          faction: "guild", cost: 10 },
  { name: "Indebted",          identifier: "guild-indebted-a",        faction: "guild", cost: 11 },
  { name: "Indebted",          identifier: "guild-indebted-b",        faction: "guild", cost: 11 },
  { name: "Mariner",           identifier: "guild-mariner-a",         faction: "guild", cost: 10 },
  { name: "Mariner",           identifier: "guild-mariner-b",         faction: "guild", cost: 10 },
  { name: "Ostrich Rider",     identifier: "guild-ostrich-rider",     faction: "guild", cost: 12 },
  { name: "Pilferer",          identifier: "guild-pilferer-a",        faction: "guild", cost: 10 },
  { name: "Pilferer",          identifier: "guild-pilferer-b",        faction: "guild", cost: 10 },
  { name: "Citizen",           identifier: "guild-citizen-a",         faction: "guild", cost:  9 },
  { name: "Citizen",           identifier: "guild-citizen-b",         faction: "guild", cost:  9 },
  { name: "Dog Keeper",        identifier: "guild-dog-keeper",        faction: "guild", cost: 12 },
  { name: "Dog",               identifier: "guild-dog-a",             faction: "guild", cost:  5 },
  { name: "Dog",               identifier: "guild-dog-b",             faction: "guild", cost:  5 },

  # Patricians
  { name: "Pinnacle of Affluence",  identifier: "patricians-pinnacle-of-affluence",  faction: "patricians", cost: 32 },
  { name: "Guard Commander",        identifier: "patricians-guard-commander",        faction: "patricians", cost: 20 },
  { name: "Noble Admiral",          identifier: "patricians-noble-admiral",          faction: "patricians", cost: 19 },
  { name: "Venetian Noble",         identifier: "patricians-venetian-noble",         faction: "patricians", cost: 21 },
  { name: "Mounted Venetian Noble", identifier: "patricians-mounted-venetian-noble", faction: "patricians", cost: 24 },
  { name: "Janissary Chorbaji",     identifier: "patricians-janissary-chorbaji",     faction: "patricians", cost: 23 },
  { name: "Sopracomito",            identifier: "patricians-sopracomito",            faction: "patricians", cost: 15 },
  { name: "Don Gregorio Morisini",  identifier: "patricians-don-gregorio-morisini",  faction: "patricians", cost: 18 },
  { name: "Moon",                   identifier: "patricians-moon",                   faction: "patricians", cost: 16 },
  { name: "Sun",                    identifier: "patricians-sun",                    faction: "patricians", cost: 15 },
  { name: "Adventuring Noble",      identifier: "patricians-adventuring-noble",      faction: "patricians", cost: 16 },
  { name: "Captain of the Guard",   identifier: "patricians-captain-of-the-guard",   faction: "patricians", cost: 14 },
  { name: "Cat Burglar",            identifier: "patricians-cat-burglar",            faction: "patricians", cost: 15 },
  { name: "Fencing Master",         identifier: "patricians-fencing-master",         faction: "patricians", cost: 16 },
  { name: "Foreign Dignitary",      identifier: "patricians-foreign-dignitary",      faction: "patricians", cost: 14 },
  { name: "Gourmand Noble",         identifier: "patricians-gourmand-noble",         faction: "patricians", cost: 13 },
  { name: "Naval Lieutenant",       identifier: "patricians-naval-lieutenant",       faction: "patricians", cost: 15 },
  { name: "Janissary Sapper",       identifier: "patricians-janissary-sapper",       faction: "patricians", cost: 16 },
  { name: "Ottoman Cannoneer",      identifier: "patricians-ottoman-cannoneer",      faction: "patricians", cost: 15 },
  { name: "Ottoman Janissary",      identifier: "patricians-ottoman-janissary-a",    faction: "patricians", cost: 17 },
  { name: "Ottoman Janissary",      identifier: "patricians-ottoman-janissary-b",    faction: "patricians", cost: 17 },
  { name: "Seven Years Veteran",    identifier: "patricians-seven-years-veteran",    faction: "patricians", cost: 15 },
  { name: "Submissive Noble",       identifier: "patricians-submissive-noble",       faction: "patricians", cost: 17 },
  { name: "Syphilitic Noble",       identifier: "patricians-syphilitic-noble",       faction: "patricians", cost: 13 },
  { name: "Venetian Heavy Guard",   identifier: "patricians-venetian-heavy-guard",   faction: "patricians", cost: 16 },
  { name: "Venetian Spy",           identifier: "patricians-venetian-spy",           faction: "patricians", cost: 16 },
  { name: "Wayfinder",              identifier: "patricians-wayfinder",              faction: "patricians", cost: 12 },
  { name: "Barnabotti",             identifier: "patricians-barnabotti-a",           faction: "patricians", cost: 12 },
  { name: "Barnabotti",             identifier: "patricians-barnabotti-b",           faction: "patricians", cost: 12 },
  { name: "Butler",                 identifier: "patricians-butler-a",               faction: "patricians", cost: 10 },
  { name: "Butler",                 identifier: "patricians-butler-b",               faction: "patricians", cost: 10 },
  { name: "Cannibal Cultist",       identifier: "patricians-cannibal-cultist",       faction: "patricians", cost:  8 },
  { name: "Cortigiane",             identifier: "patricians-cortigiane-a",           faction: "patricians", cost: 12 },
  { name: "Cortigiane",             identifier: "patricians-cortigiane-b",           faction: "patricians", cost: 12 },
  { name: "City Guard",             identifier: "patricians-city-guard-a",           faction: "patricians", cost: 10 },
  { name: "City Guard",             identifier: "patricians-city-guard-b",           faction: "patricians", cost: 10 },
  { name: "Guard Marksman",         identifier: "patricians-guard-marksman",         faction: "patricians", cost: 12 },
  { name: "Guard Sentry",           identifier: "patricians-guard-sentry",           faction: "patricians", cost: 12 },
  { name: "Hired Muscle",           identifier: "patricians-hired-muscle",           faction: "patricians", cost: 11 },
  { name: "Household Staff",        identifier: "patricians-household-staff-a",      faction: "patricians", cost:  9 },
  { name: "Household Staff",        identifier: "patricians-household-staff-b",      faction: "patricians", cost:  9 },
  { name: "Hunting Hound",          identifier: "patricians-hunting-hound-a",        faction: "patricians", cost:  6 },
  { name: "Hunting Hound",          identifier: "patricians-hunting-hound-b",        faction: "patricians", cost:  6 },
  { name: "Merchant",               identifier: "patricians-merchant-a",             faction: "patricians", cost: 13 },
  { name: "Merchant",               identifier: "patricians-merchant-b",             faction: "patricians", cost: 13 },
  { name: "Naval Ensign",           identifier: "patricians-naval-ensign",           faction: "patricians", cost: 12 },
  { name: "Naval Recruit",          identifier: "patricians-naval-recruit-a",        faction: "patricians", cost:  9 },
  { name: "Naval Recruit",          identifier: "patricians-naval-recruit-b",        faction: "patricians", cost:  9 },
  { name: "Noble Seafarer",         identifier: "patricians-noble-seafarer-a",       faction: "patricians", cost: 12 },
  { name: "Noble Seafarer",         identifier: "patricians-noble-seafarer-b",       faction: "patricians", cost: 12 },
  { name: "Ottoman Archer",         identifier: "patricians-ottoman-archer",         faction: "patricians", cost: 10 },
  { name: "Ottoman Pirate",         identifier: "patricians-ottoman-pirate",         faction: "patricians", cost: 11 },
  { name: "Ottoman Rigger",         identifier: "patricians-ottoman-rigger",         faction: "patricians", cost: 12 },

  # Rashaar
  { name: "The Flame That Burns Underwater", identifier: "rashaar-the-flame-that-burns-underwater", faction: "rashaar", cost: 30 },
  { name: "Magi-Rashaar",                   identifier: "rashaar-magi-rashaar",                    faction: "rashaar", cost: 24 },
  { name: "Paartul Matriarch",              identifier: "rashaar-paartul-matriarch",               faction: "rashaar", cost: 25 },
  { name: "Sir Tiburcio",                   identifier: "rashaar-sir-tiburcio",                    faction: "rashaar", cost: 23 },
  { name: "Thalidraur",                     identifier: "rashaar-thalidraur",                      faction: "rashaar", cost: 26 },
  { name: "Voice of Dagon",                 identifier: "rashaar-voice-of-dagon",                  faction: "rashaar", cost: 20 },
  { name: "Morgraur",                       identifier: "rashaar-morgraur",                        faction: "rashaar", cost: 68 },
  { name: "Emissary of Mother Hydra",       identifier: "rashaar-emissary-of-mother-hydra",        faction: "rashaar", cost: 51 },
  { name: "Maw Tentacle",                   identifier: "rashaar-maw-tentacle",                    faction: "rashaar", cost:  0 },
  { name: "Lash Tentacle",                  identifier: "rashaar-lash-tentacle",                   faction: "rashaar", cost:  0 },
  { name: "Dagger Tentacle",                identifier: "rashaar-dagger-tentacle",                 faction: "rashaar", cost:  0 },
  { name: "Thorn Tentacle",                 identifier: "rashaar-thorn-tentacle",                  faction: "rashaar", cost:  0 },
  { name: "The Drowned Nun",                identifier: "rashaar-the-drowned-nun",                 faction: "rashaar", cost: 18 },
  { name: "Brachyura",                      identifier: "rashaar-brachyura-a",                     faction: "rashaar", cost: 18 },
  { name: "Brachyura",                      identifier: "rashaar-brachyura-b",                     faction: "rashaar", cost: 18 },
  { name: "Caandru Eel",                    identifier: "rashaar-caandru-eel",                     faction: "rashaar", cost: 14 },
  { name: "Cult Enforcer",                  identifier: "rashaar-cult-enforcer",                   faction: "rashaar", cost: 14 },
  { name: "Dagonite Priest",                identifier: "rashaar-dagonite-priest",                 faction: "rashaar", cost: 15 },
  { name: "Demagogue",                      identifier: "rashaar-demagogue",                       faction: "rashaar", cost: 15 },
  { name: "Handler",                        identifier: "rashaar-handler",                         faction: "rashaar", cost: 12 },
  { name: "Karcharos",                      identifier: "rashaar-karcharos",                       faction: "rashaar", cost: 18 },
  { name: "Krakenhost",                     identifier: "rashaar-krakenhost",                      faction: "rashaar", cost: 17 },
  { name: "Mature Kraken",                  identifier: "rashaar-mature-kraken",                   faction: "rashaar", cost: 24 },
  { name: "Paliaa",                         identifier: "rashaar-paliaa",                          faction: "rashaar", cost: 19 },
  { name: "Raadru",                         identifier: "rashaar-raadru",                          faction: "rashaar", cost: 20 },
  { name: "Salaacia",                       identifier: "rashaar-salaacia",                        faction: "rashaar", cost: 16 },
  { name: "Secreting Myxin",                identifier: "rashaar-secreting-myxin",                 faction: "rashaar", cost: 23 },
  { name: "Sirena",                         identifier: "rashaar-sirena",                          faction: "rashaar", cost: 18 },
  { name: "Tainted Maw",                    identifier: "rashaar-tainted-maw",                     faction: "rashaar", cost: 18 },
  { name: "Advanced Hybrid",                identifier: "rashaar-advanced-hybrid-a",               faction: "rashaar", cost: 12 },
  { name: "Advanced Hybrid",                identifier: "rashaar-advanced-hybrid-b",               faction: "rashaar", cost: 12 },
  { name: "Aglaope",                        identifier: "rashaar-aglaope",                         faction: "rashaar", cost: 12 },
  { name: "Bounding Telebine",              identifier: "rashaar-bounding-telebine",               faction: "rashaar", cost:  9 },
  { name: "Bulbous Toad",                   identifier: "rashaar-bulbous-toad",                    faction: "rashaar", cost: 13 },
  { name: "Crybaby",                        identifier: "rashaar-crybaby-a",                       faction: "rashaar", cost:  0 },
  { name: "Crybaby",                        identifier: "rashaar-crybaby-b",                       faction: "rashaar", cost:  0 },
  { name: "Cymothoan Crusher",              identifier: "rashaar-cymothoan-crusher",               faction: "rashaar", cost: 17 },
  { name: "Dagon Officiant",                identifier: "rashaar-dagon-officiant-a",               faction: "rashaar", cost:  0 },
  { name: "Dagon Officiant",                identifier: "rashaar-dagon-officiant-b",               faction: "rashaar", cost:  0 },
  { name: "Dagonite Page",                  identifier: "rashaar-dagonite-page",                   faction: "rashaar", cost: 13 },
  { name: "Dagonite Zealot",                identifier: "rashaar-dagonite-zealot-a",               faction: "rashaar", cost:  0 },
  { name: "Dagonite Zealot",                identifier: "rashaar-dagonite-zealot-b",               faction: "rashaar", cost:  0 },
  { name: "Encrusted Squire",               identifier: "rashaar-encrusted-squire",                faction: "rashaar", cost: 12 },
  { name: "Half-Breed",                     identifier: "rashaar-half-breed",                      faction: "rashaar", cost: 16 },
  { name: "Hellhound",                      identifier: "rashaar-hellhound",                       faction: "rashaar", cost: 10 },
  { name: "Hybrid",                         identifier: "rashaar-hybrid-a",                        faction: "rashaar", cost:  9 },
  { name: "Hybrid",                         identifier: "rashaar-hybrid-b",                        faction: "rashaar", cost:  9 },
  { name: "Infant Kraken",                  identifier: "rashaar-infant-kraken-a",                 faction: "rashaar", cost:  0 },
  { name: "Infant Kraken",                  identifier: "rashaar-infant-kraken-b",                 faction: "rashaar", cost:  0 },
  { name: "Lesser Rhyll",                   identifier: "rashaar-lesser-rhyll",                    faction: "rashaar", cost: 13 },
  { name: "Lesser Ugdru",                   identifier: "rashaar-lesser-ugdru-a",                  faction: "rashaar", cost: 14 },
  { name: "Lesser Ugdru",                   identifier: "rashaar-lesser-ugdru-b",                  faction: "rashaar", cost: 14 },
  { name: "Slave",                          identifier: "rashaar-slave-a",                         faction: "rashaar", cost:  0 },
  { name: "Slave",                          identifier: "rashaar-slave-b",                         faction: "rashaar", cost:  0 },
  { name: "Urchin",                         identifier: "rashaar-urchin-a",                        faction: "rashaar", cost:  8 },
  { name: "Urchin",                         identifier: "rashaar-urchin-b",                        faction: "rashaar", cost:  8 },
  { name: "Wet Nurse",                      identifier: "rashaar-wet-nurse",                       faction: "rashaar", cost: 10 },

  # Strigoi
  { name: "Vlad Dracula",       identifier: "strigoi-vlad-dracula",       faction: "strigoi", cost: 27 },
  { name: "Blood Crone",        identifier: "strigoi-blood-crone",        faction: "strigoi", cost: 18 },
  { name: "Noble Strigoi",      identifier: "strigoi-noble-strigoi",      faction: "strigoi", cost: 21 },
  { name: "Stryha Crone",       identifier: "strigoi-stryha-crone",       faction: "strigoi", cost: 22 },
  { name: "Wallachian Hospodar",identifier: "strigoi-wallachian-hospodar",faction: "strigoi", cost: 21 },
  { name: "Ceres",              identifier: "strigoi-ceres",              faction: "strigoi", cost: 19 },
  { name: "Cibele",             identifier: "strigoi-cibele",             faction: "strigoi", cost: 19 },
  { name: "Miriam",             identifier: "strigoi-miriam",             faction: "strigoi", cost: 19 },
  { name: "Monstrous Stryx",    identifier: "strigoi-monstrous-stryx",    faction: "strigoi", cost: 40 },
  { name: "Aquatic Strigoi",    identifier: "strigoi-aquatic-strigoi",    faction: "strigoi", cost: 14 },
  { name: "Cetean Upior",       identifier: "strigoi-cetean-upior",       faction: "strigoi", cost: 21 },
  { name: "Highborn Servant",   identifier: "strigoi-highborn-servant",   faction: "strigoi", cost: 13 },
  { name: "Hulking Moroi",      identifier: "strigoi-hulking-moroi",      faction: "strigoi", cost: 14 },
  { name: "Leech",              identifier: "strigoi-leech",              faction: "strigoi", cost: 12 },
  { name: "Moon Eater",         identifier: "strigoi-moon-eater",         faction: "strigoi", cost: 23 },
  { name: "Reaper",             identifier: "strigoi-reaper",             faction: "strigoi", cost: 13 },
  { name: "Seer",               identifier: "strigoi-seer",               faction: "strigoi", cost: 15 },
  { name: "Spatar",             identifier: "strigoi-spatar",             faction: "strigoi", cost: 16 },
  { name: "Strige",             identifier: "strigoi-strige",             faction: "strigoi", cost: 14 },
  { name: "Strigoi Jude",       identifier: "strigoi-strigoi-jude",       faction: "strigoi", cost: 18 },
  { name: "Strigoi Priest",     identifier: "strigoi-strigoi-priest",     faction: "strigoi", cost: 14 },
  { name: "Targoveti",          identifier: "strigoi-targoveti-a",        faction: "strigoi", cost: 10 },
  { name: "Targoveti",          identifier: "strigoi-targoveti-b",        faction: "strigoi", cost: 10 },
  { name: "Thrall",             identifier: "strigoi-thrall-a",           faction: "strigoi", cost:  9 },
  { name: "Thrall",             identifier: "strigoi-thrall-b",           faction: "strigoi", cost:  9 },
  { name: "Strigoi Sluger",     identifier: "strigoi-strigoi-sluger",     faction: "strigoi", cost: 18 },
  { name: "Strzyga",            identifier: "strigoi-strzyga",            faction: "strigoi", cost: 18 },
  { name: "Tarot Reader",       identifier: "strigoi-tarot-reader",       faction: "strigoi", cost: 16 },
  { name: "Varcolac",           identifier: "strigoi-varcolac",           faction: "strigoi", cost: 17 },
  { name: "Wallachian Impaler", identifier: "strigoi-wallachian-impaler", faction: "strigoi", cost: 18 },
  { name: "Zoryi",              identifier: "strigoi-zoryi",              faction: "strigoi", cost: 19 },
  { name: "Al Naibii",          identifier: "strigoi-al-naibii",          faction: "strigoi", cost:  9 },
  { name: "Common Strigoi",     identifier: "strigoi-common-strigoi-a",   faction: "strigoi", cost: 13 },
  { name: "Common Strigoi",     identifier: "strigoi-common-strigoi-b",   faction: "strigoi", cost: 13 },
  { name: "Ferryman",           identifier: "strigoi-ferryman-a",         faction: "strigoi", cost:  9 },
  { name: "Ferryman",           identifier: "strigoi-ferryman-b",         faction: "strigoi", cost:  9 },
  { name: "Giurgiu Guard",      identifier: "strigoi-giurgiu-guard-a",    faction: "strigoi", cost: 13 },
  { name: "Giurgiu Guard",      identifier: "strigoi-giurgiu-guard-b",    faction: "strigoi", cost: 13 },
  { name: "Harpy",              identifier: "strigoi-harpy-a",            faction: "strigoi", cost:  6 },
  { name: "Harpy",              identifier: "strigoi-harpy-b",            faction: "strigoi", cost:  6 },
  { name: "Newborn Strigoi",    identifier: "strigoi-newborn-strigoi",    faction: "strigoi", cost:  8 },
  { name: "Nosferatu",          identifier: "strigoi-nosferatu-a",        faction: "strigoi", cost: 13 },
  { name: "Nosferatu",          identifier: "strigoi-nosferatu-b",        faction: "strigoi", cost: 13 },
  { name: "Romani",             identifier: "strigoi-romani-a",           faction: "strigoi", cost:  9 },
  { name: "Romani",             identifier: "strigoi-romani-b",           faction: "strigoi", cost:  9 },
  { name: "Rotter",             identifier: "strigoi-rotter-a",           faction: "strigoi", cost: 12 },
  { name: "Rotter",             identifier: "strigoi-rotter-b",           faction: "strigoi", cost: 12 },
  { name: "Sinker",             identifier: "strigoi-sinker-a",           faction: "strigoi", cost: 10 },
  { name: "Sinker",             identifier: "strigoi-sinker-b",           faction: "strigoi", cost: 10 },
  { name: "Starved Dhampir",    identifier: "strigoi-starved-dhampir",    faction: "strigoi", cost:  7 },
  { name: "Poenari Scout",      identifier: "strigoi-poenari-scout",      faction: "strigoi", cost: 12 },

  # Vatican
  { name: "Patriarch Bishop de Bernis",   identifier: "vatican-patriarch-bishop-de-bernis",   faction: "vatican", cost: 24 },
  { name: "Father Cesta",                 identifier: "vatican-father-cesta",                 faction: "vatican", cost: 24 },
  { name: "Exorcist",                     identifier: "vatican-exorcist",                     faction: "vatican", cost: 20 },
  { name: "Inquisitor",                   identifier: "vatican-inquisitor",                   faction: "vatican", cost: 22 },
  { name: "Knight Commander",             identifier: "vatican-knight-commander",             faction: "vatican", cost: 21 },
  { name: "Angel of the Blooded Rose",    identifier: "vatican-angel-of-the-blooded-rose",    faction: "vatican", cost: 20 },
  { name: "Felix Baumgartner",            identifier: "vatican-felix-baumgartner",            faction: "vatican", cost: 17 },
  { name: "Gethsemane",                   identifier: "vatican-gethsemane",                   faction: "vatican", cost: 37 },
  { name: "Eater of Sin",                 identifier: "vatican-eater-of-sin",                 faction: "vatican", cost: 16 },
  { name: "Avignon Guard",                identifier: "vatican-avignon-guard",                faction: "vatican", cost: 14 },
  { name: "Baptist",                      identifier: "vatican-baptist",                      faction: "vatican", cost: 15 },
  { name: "Burning Saint",                identifier: "vatican-burning-saint",                faction: "vatican", cost: 16 },
  { name: "Conventual Chaplain",          identifier: "vatican-conventual-chaplain",          faction: "vatican", cost: 13 },
  { name: "Cross-bearing Deacon",         identifier: "vatican-cross-bearing-deacon",         faction: "vatican", cost: 14 },
  { name: "Divine Seraphim",              identifier: "vatican-divine-seraphim",              faction: "vatican", cost: 18 },
  { name: "Executioner",                  identifier: "vatican-executioner",                  faction: "vatican", cost: 12 },
  { name: "Galilean Priest",              identifier: "vatican-galilean-priest",              faction: "vatican", cost: 17 },
  { name: "Golgotha",                     identifier: "vatican-golgotha",                     faction: "vatican", cost: 18 },
  { name: "Inquisition Commissioner",     identifier: "vatican-inquisition-commissioner",     faction: "vatican", cost: 16 },
  { name: "Knight of the Holy Sepulchre", identifier: "vatican-knight-of-the-holy-sepulchre", faction: "vatican", cost: 17 },
  { name: "Paladin of St Lazarus",        identifier: "vatican-paladin-of-st-lazarus",        faction: "vatican", cost: 16 },
  { name: "Prelate of the Flaming Sword", identifier: "vatican-prelate-of-the-flaming-sword", faction: "vatican", cost: 15 },
  { name: "Scorpio Marksman",             identifier: "vatican-scorpio-marksman",             faction: "vatican", cost: 15 },
  { name: "Sepulchral Vanguard",          identifier: "vatican-sepulchral-vanguard",          faction: "vatican", cost: 15 },
  { name: "Seraph",                       identifier: "vatican-seraph",                       faction: "vatican", cost: 17 },
  { name: "Silere Priest",                identifier: "vatican-silere-priest",                faction: "vatican", cost: 16 },
  { name: "Stigmatist",                   identifier: "vatican-stigmatist",                   faction: "vatican", cost: 13 },
  { name: "Summoner Priest",              identifier: "vatican-summoner-priest",              faction: "vatican", cost: 15 },
  { name: "Templar Marshal",              identifier: "vatican-templar-marshal",              faction: "vatican", cost: 14 },
  { name: "Throne",                       identifier: "vatican-throne",                       faction: "vatican", cost: 22 },
  { name: "Venator of Devotion",          identifier: "vatican-venator-of-devotion",          faction: "vatican", cost: 17 },
  { name: "French Infantryman",           identifier: "vatican-french-infantryman-a",         faction: "vatican", cost:  9 },
  { name: "French Infantryman",           identifier: "vatican-french-infantryman-b",         faction: "vatican", cost:  9 },
  { name: "Inquisitorial Spy",            identifier: "vatican-inquisitorial-spy",            faction: "vatican", cost:  9 },
  { name: "Knight of Malta",              identifier: "vatican-knight-of-malta-a",            faction: "vatican", cost: 14 },
  { name: "Knight of Malta",              identifier: "vatican-knight-of-malta-b",            faction: "vatican", cost: 14 },
  { name: "Lacrimosa",                    identifier: "vatican-lacrimosa",                    faction: "vatican", cost: 10 },
  { name: "Maltese Squire",               identifier: "vatican-maltese-squire-a",             faction: "vatican", cost: 10 },
  { name: "Maltese Squire",               identifier: "vatican-maltese-squire-b",             faction: "vatican", cost: 10 },
  { name: "Martyr",                       identifier: "vatican-martyr-a",                     faction: "vatican", cost:  8 },
  { name: "Martyr",                       identifier: "vatican-martyr-b",                     faction: "vatican", cost:  8 },
  { name: "Priest",                       identifier: "vatican-priest-a",                     faction: "vatican", cost: 10 },
  { name: "Priest",                       identifier: "vatican-priest-b",                     faction: "vatican", cost: 10 },
  { name: "Redemptionist",                identifier: "vatican-redemptionist-a",              faction: "vatican", cost: 12 },
  { name: "Redemptionist",                identifier: "vatican-redemptionist-b",              faction: "vatican", cost: 12 },
  { name: "Stalker",                      identifier: "vatican-stalker",                      faction: "vatican", cost: 12 },
  { name: "Thalassic Messenger",          identifier: "vatican-thalassic-messenger",          faction: "vatican", cost: 18 },
  { name: "Theophant of Sinai",           identifier: "vatican-theophant-of-sinai",           faction: "vatican", cost: 13 },
  { name: "Witch Finder",                 identifier: "vatican-witch-finder",                 faction: "vatican", cost: 12 },
  { name: "Thomas Thieme",                identifier: "vatican-thomas-thieme",                faction: "vatican", cost: 13 },
  { name: "Altar Boy",                    identifier: "vatican-altar-boy-a",                  faction: "vatican", cost:  8 },
  { name: "Altar Boy",                    identifier: "vatican-altar-boy-b",                  faction: "vatican", cost:  8 },
  { name: "Bishop Guard",                 identifier: "vatican-bishop-guard-a",               faction: "vatican", cost: 11 },
  { name: "Bishop Guard",                 identifier: "vatican-bishop-guard-b",               faction: "vatican", cost: 11 },
  { name: "Celestial Congregation",       identifier: "vatican-celestial-congregation",       faction: "vatican", cost: 15 },
  { name: "Celestial Spirit",             identifier: "vatican-celestial-spirit-a",           faction: "vatican", cost: 10 },
  { name: "Celestial Spirit",             identifier: "vatican-celestial-spirit-b",           faction: "vatican", cost: 10 },
  { name: "Cherubim",                     identifier: "vatican-cherubim-a",                   faction: "vatican", cost:  8 },
  { name: "Cherubim",                     identifier: "vatican-cherubim-b",                   faction: "vatican", cost:  8 },
  { name: "Chevaleresse",                 identifier: "vatican-chevaleresse-a",               faction: "vatican", cost: 11 },
  { name: "Chevaleresse",                 identifier: "vatican-chevaleresse-b",               faction: "vatican", cost: 11 },
  { name: "Crucifier",                    identifier: "vatican-crucifier",                    faction: "vatican", cost: 10 },
  { name: "Reliquary Page",               identifier: "vatican-reliquary-page",               faction: "vatican", cost:  9 }
]

records = references.map do |attrs|
  name = case attrs[:identifier]
         when /-a$/ then "#{attrs[:name]} (A)"
         when /-b$/ then "#{attrs[:name]} (B)"
         else attrs[:name]
         end

  now = Time.current
  { name: name, identifier: attrs[:identifier], faction: attrs[:faction], cost: attrs[:cost], created_at: now, updated_at: now }
end

Reference.upsert_all(records, unique_by: :identifier, update_only: %i[name faction cost])

puts "Seeded #{Reference.count} references"
